"""empty message

Revision ID: 16bde0dbe7df
Revises: c38016f130c2
Create Date: 2025-04-08 09:35:09.317273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16bde0dbe7df'
down_revision = 'c38016f130c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crypto_currency', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['coin_gecko_currency_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crypto_currency', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
