"""empty message

Revision ID: 5d35943a53d5
Revises: 63ec5ecf2d3a
Create Date: 2025-04-07 18:25:14.467175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d35943a53d5'
down_revision = '63ec5ecf2d3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coing_gecko_currency', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('symbol',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coing_gecko_currency', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('symbol',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
