"""empty message

Revision ID: 63ec5ecf2d3a
Revises: 800384657cb8
Create Date: 2025-04-07 17:58:57.202871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63ec5ecf2d3a'
down_revision = '800384657cb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coing_gecko_currency',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coing_gecko_currency', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coing_gecko_currency_symbol'), ['symbol'], unique=True)

    with op.batch_alter_table('crypto_currency', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_constraint('crypto_currency_symbol_key', type_='unique')
        batch_op.drop_column('name')
        batch_op.drop_column('symbol')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crypto_currency', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symbol', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('crypto_currency_symbol_key', ['symbol'])
        batch_op.alter_column('image',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('coing_gecko_currency', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coing_gecko_currency_symbol'))

    op.drop_table('coing_gecko_currency')
    # ### end Alembic commands ###
