"""empty message

Revision ID: b33b6a1c859f
Revises: 5d35943a53d5
Create Date: 2025-04-07 18:28:37.703956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b33b6a1c859f'
down_revision = '5d35943a53d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coing_gecko_currency', schema=None) as batch_op:
        batch_op.drop_index('ix_coing_gecko_currency_symbol')
        batch_op.create_index(batch_op.f('ix_coing_gecko_currency_symbol'), ['symbol'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coing_gecko_currency', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coing_gecko_currency_symbol'))
        batch_op.create_index('ix_coing_gecko_currency_symbol', ['symbol'], unique=True)

    # ### end Alembic commands ###
